session_name: AoC_2023
start_directory: ./
windows:
  - window_name: python
    layout: 6736,239x73,0,0[239x57,0,0,1,239x15,0,58{119x15,0,58,2,119x15,120,58,3}]
    focus: True
    start_directory: ./
    panes:
      - focus: True
        shell_command:
          - nvim .
      -
      -
